#ifndef UI_MANAGER_H
#define UI_MANAGER_H

#include <stdbool.h>

typedef enum {
    SCREEN_NONE,
    SCREEN_HOME,
    SCREEN_MENU,
    SCREEN_WIFI_MENU,
    SCREEN_WIFI_ATTACK_MENU,
    SCREEN_WIFI_DEAUTH_ATTACK,
    SCREEN_WIFI_DEAUTH_UNICAST,
    SCREEN_WIFI_BEACON_SPAM_SIMPLE,
    SCREEN_WIFI_PROBE_FLOOD,
    SCREEN_WIFI_PROBE_FLOOD_BROADCAST,
    SCREEN_WIFI_PROBE_FLOOD_UNICAST,
    SCREEN_WIFI_AUTH_FLOOD,
    SCREEN_WIFI_PACKETS_MENU,
    SCREEN_WIFI_SNIFFER_RAW,
    SCREEN_WIFI_SNIFFER_ATTACK,
    SCREEN_WIFI_SNIFFER_HANDSHAKE,
    SCREEN_WIFI_SCAN_MENU,
    SCREEN_WIFI_SCAN_AP,
    SCREEN_WIFI_SCAN_STATIONS,
    SCREEN_WIFI_SCAN_TARGET,
    SCREEN_WIFI_SCAN_PROBE,
    SCREEN_WIFI_SCAN_MONITOR,
    SCREEN_WIFI_SCAN,
    SCREEN_WIFI_AP_LIST,
    SCREEN_WIFI_DEAUTH,
    SCREEN_WIFI_EVIL_TWIN,
    SCREEN_WIFI_BEACON_SPAM,
    SCREEN_WIFI_PROBE,
    SCREEN_BLE_MENU,
    SCREEN_BLE_SPAM_SELECT,
    SCREEN_BLE_SPAM,
    SCREEN_BADUSB_MENU,
    SCREEN_BADUSB_BROWSER,
    SCREEN_BADUSB_LAYOUT,
    SCREEN_BADUSB_CONNECT,
    SCREEN_BADUSB_RUNNING,
    SCREEN_SUBGHZ_SPECTRUM,
    SCREEN_SETTINGS,
    SCREEN_DISPLAY_SETTINGS,
    SCREEN_INTERFACE_SETTINGS,
    SCREEN_SOUND_SETTINGS,
    SCREEN_BATTERY_SETTINGS,
    SCREEN_CONNECTION_SETTINGS,
    SCREEN_CONNECT_WIFI,
    SCREEN_CONNECT_BLUETOOTH,
    SCREEN_ABOUT_SETTINGS,
    SCREEN_NFC_MENU,
    SCREEN_FILES,
    SCREEN_THEME_SELECTOR,
    SCREEN_IR_MENU,
    SCREEN_IR_RECEIVE,
    SCREEN_IR_SEND,
    SCREEN_IR_CONTROLLER,
    SCREEN_IR_SAVED,
    SCREEN_IR_BURST
    // others screens
} screen_id_t;

void ui_init(void);
void ui_hard_restart(void);

bool ui_acquire(void);
void ui_release(void);
void ui_switch_screen(screen_id_t new_screen);

bool ui_input_is_locked(void);

#endif


